name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autotools-dev automake
    - name: Generate configure script
      run: autoreconf -i
    - name: Configure the project
      run: ./configure
    - name: Build the project
      run: make
    - name: Run tests
      run: make check
    - name: Run distcheck (optional)
      run: make distcheck
